### PR TITLE
Ignore screenshots and a few warnings

### PR DESCRIPTION
**Pull request by aaronfranke**
This prevents screenshots from being imported, and I also silenced a few warnings. See this article for more information: https://docs.godotengine.org/en/latest/tutorials/assetlib/uploading_to_assetlib.html

By the way, why is the EOL setting set to CRLF? It's a good practice to use LF everywhere, it takes up less disk space and it's what Godot uses when creating new files.

### CODE REVIEW

**Comment by manglemix** [comment]
Oh dear, I think CRLF was a mistake. I believe I was trying to set it to LF because my github desktop was getting messed up

**Review by manglemix — APPROVED** [review]
Frankly I wasn't aware that you could prepend an argument with an underscore if it was being overriden and the new function doesn't use an underscore. I will definitely remember to use these warning ignores in the future

**Comment by aaronfranke** [comment]
I pushed a 2nd commit changing it to `eol=lf`, and I also took the liberty of changing `README.md` to be formatting-script-friendly (The backslash `\` is an alternative to two spaces for escaping newlines and it doesn't require trailing spaces).

**Comment by manglemix** [comment]
Thank you for reviewing my package, I'm trying to open up more to the community, and I appreciate people going through my work to improve it

**Comment by aaronfranke** [comment]
If you want another suggestion, consider using a better Git client. GitHub Desktop is not very good. Personally I use [GitKraken](https://www.gitkraken.com/) (it's free for public repos) and I also made a video explaining how to use it; https://www.youtube.com/watch?v=0XKy8YpP5Ww

**Pull request merged**
